import React from 'react';
import {
   
} from 'react-router-dom'

import Transaction from './Transaction'

class Transactions extends React.Component {
    constructor() {
        super();
        this.state = {
            loaded: false,
            transactions: 
                  [
                    {
                      "transaction_id": "a4dd85c3-d2ef-45d9-82aa-4f2f92124d05",
                      "currency": "EUR",
                      "booking_date": "2020-12-06",
                      "value_date": "2020-12-06",
                      "type_description": "Itsepalvelu",
                      "narrative": "18110005577211",
                      "message": "18110005577211",
                      "status": "billed",
                      "reference": "181120258878060000",
                      "own_message": "18110005577211",
                      "counterparty_name": "Helsinkimissio ry",
                      "transaction_date": "2020-12-06",
                      "payment_date": "2020-12-06",
                      "amount": "-12.15"
                    },
                    {
                      "transaction_id": "928801dc-7096-497f-b76e-02094f860c6b",
                      "currency": "EUR",
                      "booking_date": "2020-12-06",
                      "value_date": "2020-12-06",
                      "type_description": "e-maksu",
                      "narrative": "01012019",
                      "message": "01012019",
                      "status": "billed",
                      "reference": "660562087011",
                      "own_message": "01012019",
                      "counterparty_name": "Cross  Sports Club",
                      "transaction_date": "2020-12-06",
                      "payment_date": "2020-12-06",
                      "amount": "-15.00"
                    },
                    {
                      "transaction_id": "48dc5c0e-e63b-405a-b249-2a99035115cf",
                      "currency": "EUR",
                      "booking_date": "2020-12-06",
                      "value_date": "2020-12-06",
                      "type_description": "Korttiosto",
                      "narrative": "DKK 49,00 Kastrup",
                      "message": "DKK 49,00 Kastrup",
                      "status": "billed",
                      "reference": "181114280444",
                      "own_message": "DKK 49,00 Kastrup",
                      "counterparty_name": "Gebr Heinemann Retail",
                      "transaction_date": "2020-12-06",
                      "card_number": "1234",
                      "payment_date": "2020-12-06",
                      "original_currency": "DKK",
                      "original_currency_amount": "49.00",
                      "currency_rate": "7.2917",
                      "amount": "-6.25"
                    },
                    {
                      "transaction_id": "c64f83dc-1c50-466e-9184-0757dccd0439",
                      "currency": "EUR",
                      "booking_date": "2020-12-06",
                      "value_date": "2020-12-06",
                      "type_description": "Itsepalvelu",
                      "narrative": "Kino ",
                      "message": "Kino",
                      "status": "billed",
                      "reference": "671232100994",
                      "own_message": "Kino",
                      "counterparty_name": "Salo Johanna",
                      "transaction_date": "2020-12-06",
                      "payment_date": "2020-12-06",
                      "amount": "-0.17"
                    },
                    {
                      "transaction_id": "21c0751c-75ca-4898-b3ad-727a5692ac54",
                      "currency": "EUR",
                      "booking_date": "2020-12-06",
                      "value_date": "2020-12-06",
                      "type_description": "Mibiilimaksu",
                      "narrative": "For present to Johanna",
                      "message": "For present to Johanna",
                      "status": "billed",
                      "reference": "221127000000",
                      "own_message": "For present to Johanna",
                      "counterparty_name": "Salo Ari",
                      "transaction_date": "2020-12-06",
                      "payment_date": "2020-12-06",
                      "amount": "-0.80"
                    },
                    {
                      "transaction_id": "54492ddf-644e-41d4-b184-dce5ca1a0cfc",
                      "currency": "EUR",
                      "booking_date": "2020-12-05",
                      "value_date": "2020-12-05",
                      "type_description": "e-maksu",
                      "narrative": "01012019",
                      "message": "01012019",
                      "status": "billed",
                      "reference": "660562087011",
                      "own_message": "01012019",
                      "counterparty_name": "Cross  Sports Club",
                      "transaction_date": "2020-12-05",
                      "payment_date": "2020-12-05",
                      "amount": "-52.00"
                    },
                    {
                      "transaction_id": "2016857e-f59b-4402-91de-ae9d617262d4",
                      "currency": "EUR",
                      "booking_date": "2020-12-05",
                      "value_date": "2020-12-05",
                      "type_description": "Pano",
                      "narrative": "Rent",
                      "message": "Rent",
                      "status": "billed",
                      "reference": "221127019888",
                      "own_message": "Rent",
                      "counterparty_name": "SMM Appartments",
                      "transaction_date": "2020-12-05",
                      "payment_date": "2020-12-05",
                      "amount": "47.30"
                    },
                    {
                      "transaction_id": "b31438fd-359b-4845-a3f4-6af3f87aa0e5",
                      "currency": "EUR",
                      "booking_date": "2020-12-05",
                      "value_date": "2020-12-05",
                      "type_description": "Pano",
                      "narrative": "Rent",
                      "message": "Rent",
                      "status": "billed",
                      "reference": "221127019888",
                      "own_message": "Rent",
                      "counterparty_name": "SMM Appartments",
                      "transaction_date": "2020-12-05",
                      "payment_date": "2020-12-05",
                      "amount": "4.95"
                    },
                    {
                      "transaction_id": "b4a45c69-bd7f-4f17-9fb5-52cc300bb4a8",
                      "currency": "EUR",
                      "booking_date": "2020-12-04",
                      "value_date": "2020-12-04",
                      "type_description": "Pano",
                      "narrative": "Lapsilisä",
                      "message": "Lapsilisä",
                      "status": "billed",
                      "reference": "LL4200K6790",
                      "own_message": "Lapsilisä",
                      "counterparty_name": "KELA/FPA",
                      "transaction_date": "2020-12-04",
                      "payment_date": "2020-12-04",
                      "amount": "22.45"
                    },
                    {
                      "transaction_id": "3b6492a2-3cef-40b9-81fc-8ddf10357c93",
                      "currency": "EUR",
                      "booking_date": "2020-12-04",
                      "value_date": "2020-12-04",
                      "type_description": "Pano",
                      "narrative": "Rent",
                      "message": "Rent",
                      "status": "billed",
                      "reference": "221127019888",
                      "own_message": "Rent",
                      "counterparty_name": "SMM Appartments",
                      "transaction_date": "2020-12-04",
                      "payment_date": "2020-12-04",
                      "amount": "39.60"
                    },
                    {
                      "transaction_id": "50e93602-54c1-4157-9789-26b1ebafdf12",
                      "currency": "EUR",
                      "booking_date": "2020-12-04",
                      "value_date": "2020-12-04",
                      "type_description": "Itsepalvelu",
                      "narrative": "Mobile phone",
                      "message": "Mobile phone",
                      "status": "billed",
                      "reference": "447711118878060000",
                      "own_message": "Mobile phone",
                      "counterparty_name": "Salo Johanna",
                      "transaction_date": "2020-12-04",
                      "payment_date": "2020-12-04",
                      "amount": "-114.00"
                    },
                    {
                      "transaction_id": "3dfe5b76-4991-4c0e-8b50-c152d9b396df",
                      "currency": "EUR",
                      "booking_date": "2020-12-03",
                      "value_date": "2020-12-04",
                      "type_description": "Korttiosto",
                      "narrative": "USD 9.39 Gotham City",
                      "message": "USD 9.39 Gotham City",
                      "status": "billed",
                      "reference": "678944335600",
                      "own_message": "USD 9.39 Gotham City",
                      "counterparty_name": "Wallmart",
                      "transaction_date": "2020-12-03",
                      "card_number": "1234.0",
                      "payment_date": "2020-12-03",
                      "original_currency": "USD",
                      "original_currency_amount": "9.39",
                      "currency_rate": "1.1729",
                      "amount": "-1.76"
                    },
                    {
                      "transaction_id": "1d7be875-4063-4f1e-a67a-af5e17ecb430",
                      "currency": "EUR",
                      "booking_date": "2020-12-03",
                      "value_date": "2020-12-03",
                      "type_description": "Mibiilimaksu",
                      "narrative": "For present to Johanna",
                      "message": "For present to Johanna",
                      "status": "billed",
                      "reference": "221127000000",
                      "own_message": "For present to Johanna",
                      "counterparty_name": "Salo Ari",
                      "transaction_date": "2020-12-03",
                      "payment_date": "2020-12-03",
                      "amount": "-4.75"
                    },
                    {
                      "transaction_id": "e8f66cd3-6245-4e62-8572-30eb53056058",
                      "currency": "EUR",
                      "booking_date": "2020-12-03",
                      "value_date": "2020-12-03",
                      "type_description": "e-maksu",
                      "narrative": "01012019",
                      "message": "01012019",
                      "status": "billed",
                      "reference": "660562087011",
                      "own_message": "01012019",
                      "counterparty_name": "Cross  Sports Club",
                      "transaction_date": "2020-12-03",
                      "payment_date": "2020-12-03",
                      "amount": "-27.50"
                    },
                    {
                      "transaction_id": "464f8ecd-e98c-4d37-aca0-edc2c953cb6e",
                      "currency": "EUR",
                      "booking_date": "2020-12-03",
                      "value_date": "2020-12-03",
                      "type_description": "Korttiosto",
                      "narrative": "USD 9.39 Gotham City",
                      "message": "USD 9.39 Gotham City",
                      "status": "billed",
                      "reference": "678944335600",
                      "own_message": "USD 9.39 Gotham City",
                      "counterparty_name": "Wallmart",
                      "transaction_date": "2020-12-03",
                      "card_number": "1234.0",
                      "payment_date": "2020-12-03",
                      "original_currency": "USD",
                      "original_currency_amount": "9.39",
                      "currency_rate": "1.1729",
                      "amount": "-4.25"
                    },
                    {
                      "transaction_id": "d7ed1bb9-26b6-45b3-8484-8546c2f6775b",
                      "currency": "EUR",
                      "booking_date": "2020-12-03",
                      "value_date": "2020-12-03",
                      "type_description": "Debet automaattiotto",
                      "narrative": "EUR 20.00 Vasa",
                      "message": "EUR 20.00 Vasa",
                      "status": "billed",
                      "reference": "101015553332",
                      "own_message": "EUR 20.00 Vasa",
                      "counterparty_name": "ATM 2312",
                      "transaction_date": "2020-12-03",
                      "card_number": "1234",
                      "payment_date": "2020-12-03",
                      "amount": "-11.80"
                    },
                    {
                      "transaction_id": "e11a431c-d01f-41bf-86f1-bd65c8da9349",
                      "currency": "EUR",
                      "booking_date": "2020-12-02",
                      "value_date": "2020-12-02",
                      "type_description": "Debet automaattiotto",
                      "narrative": "EUR 35.00 Helsinki",
                      "message": "EUR 35.00 Helsinki",
                      "status": "billed",
                      "reference": "550772345",
                      "own_message": "EUR 35.00 Helsinki",
                      "counterparty_name": "ATM Nosto 1212",
                      "transaction_date": "2020-12-02",
                      "card_number": "1234",
                      "payment_date": "2020-12-02",
                      "amount": "-18.20"
                    },
                    {
                      "transaction_id": "b78ace14-c12b-4dfb-b44d-c501cc4e5896",
                      "currency": "EUR",
                      "booking_date": "2020-12-02",
                      "value_date": "2020-12-02",
                      "type_description": "Oma siirto",
                      "narrative": "Lahjat",
                      "message": "Lahjat",
                      "status": "billed",
                      "own_message": "Lahjat",
                      "counterparty_name": "Salo Ari",
                      "transaction_date": "2020-12-02",
                      "payment_date": "2020-12-02",
                      "amount": "26.80"
                    },
                    {
                      "transaction_id": "8bc1cc75-ae3d-45de-9076-529c25745254",
                      "currency": "EUR",
                      "booking_date": "2020-12-02",
                      "value_date": "2020-12-02",
                      "type_description": "Itsepalvelu",
                      "narrative": "Mobile phone",
                      "message": "Mobile phone",
                      "status": "billed",
                      "reference": "447711118878060000",
                      "own_message": "Mobile phone",
                      "counterparty_name": "Salo Johanna",
                      "transaction_date": "2020-12-02",
                      "payment_date": "2020-12-02",
                      "amount": "-49.50"
                    },
                    {
                      "transaction_id": "8193e9d7-d86a-4bed-a7e3-454278421dcc",
                      "currency": "EUR",
                      "booking_date": "2020-12-02",
                      "value_date": "2020-12-02",
                      "type_description": "Pano",
                      "narrative": "Kiitos",
                      "message": "Kiitos",
                      "status": "billed",
                      "reference": "111144419244",
                      "own_message": "Kiitos",
                      "counterparty_name": "Simon Baker",
                      "transaction_date": "2020-12-02",
                      "payment_date": "2020-12-02",
                      "amount": "1.00"
                    },
                    {
                      "transaction_id": "b60bf63e-1d69-4717-9a95-cd14dab62c97",
                      "currency": "EUR",
                      "booking_date": "2020-12-02",
                      "value_date": "2020-12-02",
                      "type_description": "e-maksu",
                      "narrative": "01012019",
                      "message": "01012019",
                      "status": "billed",
                      "reference": "660562087011",
                      "own_message": "01012019",
                      "counterparty_name": "Cross  Sports Club",
                      "transaction_date": "2020-12-02",
                      "payment_date": "2020-12-02",
                      "amount": "-11.00"
                    },
                    {
                      "transaction_id": "25dbad52-5a35-49fe-bf07-b46000784b5a",
                      "currency": "EUR",
                      "booking_date": "2020-12-02",
                      "value_date": "2020-12-02",
                      "type_description": "Korttiosto",
                      "narrative": "GBP 31.20 Heathrow",
                      "message": "GBP 31.20 Heathrow",
                      "status": "billed",
                      "reference": "795622333023",
                      "own_message": "GBP 31.20 Heathrow",
                      "counterparty_name": "Avis",
                      "transaction_date": "2020-12-02",
                      "card_number": "1234.0",
                      "payment_date": "2020-12-02",
                      "original_currency": "GBP",
                      "original_currency_amount": "31.20",
                      "currency_rate": "0.8756",
                      "amount": "-23.52"
                    },
                    {
                      "transaction_id": "5b2a506e-be4b-419c-bde0-427e809ee1f6",
                      "currency": "EUR",
                      "booking_date": "2020-12-02",
                      "value_date": "2020-12-02",
                      "type_description": "Pano",
                      "narrative": "Kiitos",
                      "message": "Kiitos",
                      "status": "billed",
                      "reference": "111144419244",
                      "own_message": "Kiitos",
                      "counterparty_name": "Simon Baker",
                      "transaction_date": "2020-12-02",
                      "payment_date": "2020-12-02",
                      "amount": "2.10"
                    },
                    {
                      "transaction_id": "e91908e5-7882-454b-a901-817789f2f559",
                      "currency": "EUR",
                      "booking_date": "2020-12-01",
                      "value_date": "2020-12-01",
                      "type_description": "Oma siirto",
                      "narrative": "Lahjat",
                      "message": "Lahjat",
                      "status": "billed",
                      "own_message": "Lahjat",
                      "counterparty_name": "Salo Ari",
                      "transaction_date": "2020-12-01",
                      "payment_date": "2020-12-01",
                      "amount": "30.00"
                    },
                    {
                      "transaction_id": "4ec3e701-662f-4aef-9154-d120c4944403",
                      "currency": "EUR",
                      "booking_date": "2020-12-01",
                      "value_date": "2020-12-01",
                      "type_description": "Pano",
                      "narrative": "Lapsilisä",
                      "message": "Lapsilisä",
                      "status": "billed",
                      "reference": "LL4200K6790",
                      "own_message": "Lapsilisä",
                      "counterparty_name": "KELA/FPA",
                      "transaction_date": "2020-12-01",
                      "payment_date": "2020-12-01",
                      "amount": "81.18"
                    },
                    {
                      "transaction_id": "b59e1360-436f-444d-bb42-37a131377bf4",
                      "currency": "EUR",
                      "booking_date": "2020-12-01",
                      "value_date": "2020-12-01",
                      "type_description": "Pano",
                      "narrative": "Lapsilisä",
                      "message": "Lapsilisä",
                      "status": "billed",
                      "reference": "LL4200K6790",
                      "own_message": "Lapsilisä",
                      "counterparty_name": "KELA/FPA",
                      "transaction_date": "2020-12-01",
                      "payment_date": "2020-12-01",
                      "amount": "160.63"
                    },
                    {
                      "transaction_id": "f32cc3a2-fbbb-46fb-a8fc-307dd66a4a16",
                      "currency": "EUR",
                      "booking_date": "2020-12-01",
                      "value_date": "2020-12-01",
                      "type_description": "Mibiilimaksu",
                      "narrative": "For present to Johanna",
                      "message": "For present to Johanna",
                      "status": "billed",
                      "reference": "221127000000",
                      "own_message": "For present to Johanna",
                      "counterparty_name": "Salo Ari",
                      "transaction_date": "2020-12-01",
                      "payment_date": "2020-12-01",
                      "amount": "-2.95"
                    },
                    {
                      "transaction_id": "778cf8d2-3986-481b-b06f-7cdf6272fb5f",
                      "currency": "EUR",
                      "booking_date": "2020-12-01",
                      "value_date": "2020-12-01",
                      "type_description": "Itsepalvelu",
                      "narrative": "Mobile phone",
                      "message": "Mobile phone",
                      "status": "billed",
                      "reference": "447711118878060000",
                      "own_message": "Mobile phone",
                      "counterparty_name": "Salo Johanna",
                      "transaction_date": "2020-12-01",
                      "payment_date": "2020-12-01",
                      "amount": "-99.00"
                    },
                    {
                      "transaction_id": "ed7ddeb5-b24c-4e09-adcd-7e69d7c335df",
                      "currency": "EUR",
                      "booking_date": "2020-12-01",
                      "value_date": "2020-12-01",
                      "type_description": "Oma siirto",
                      "narrative": "Lahjat",
                      "message": "Lahjat",
                      "status": "billed",
                      "own_message": "Lahjat",
                      "counterparty_name": "Salo Ari",
                      "transaction_date": "2020-12-01",
                      "payment_date": "2020-12-01",
                      "amount": "16.40"
                    },
                    {
                      "transaction_id": "d620ba2c-a024-4368-8232-8dbf5813661a",
                      "currency": "EUR",
                      "booking_date": "2020-12-01",
                      "value_date": "2020-12-01",
                      "type_description": "Itsepalvelu",
                      "narrative": "Kino ",
                      "message": "Kino",
                      "status": "billed",
                      "reference": "671232100994",
                      "own_message": "Kino",
                      "counterparty_name": "Salo Johanna",
                      "transaction_date": "2020-12-01",
                      "payment_date": "2020-12-01",
                      "amount": "-0.08"
                    },
                    {
                      "transaction_id": "00d945d9-c234-4d09-8b0f-98c29e581b8e",
                      "currency": "EUR",
                      "booking_date": "2020-11-30",
                      "value_date": "2020-11-30",
                      "type_description": "Korttiosto",
                      "narrative": "DKK 49,00 Kastrup",
                      "message": "DKK 49,00 Kastrup",
                      "status": "billed",
                      "reference": "181114280444",
                      "own_message": "DKK 49,00 Kastrup",
                      "counterparty_name": "Gebr Heinemann Retail",
                      "transaction_date": "2020-11-30",
                      "card_number": "1234",
                      "payment_date": "2020-11-30",
                      "original_currency": "DKK",
                      "original_currency_amount": "49.00",
                      "currency_rate": "7.2917",
                      "amount": "-4.30"
                    },
                    {
                      "transaction_id": "26d62621-3b84-4aa0-be49-d3972561b66a",
                      "currency": "EUR",
                      "booking_date": "2020-11-30",
                      "value_date": "2020-11-30",
                      "type_description": "Itsepalvelu",
                      "narrative": "18110005577211",
                      "message": "18110005577211",
                      "status": "billed",
                      "reference": "181120258878060000",
                      "own_message": "18110005577211",
                      "counterparty_name": "Helsinkimissio ry",
                      "transaction_date": "2020-11-30",
                      "payment_date": "2020-11-30",
                      "amount": "-2.40"
                    },
                    {
                      "transaction_id": "fac3cba0-32a3-4b93-bb0b-b96ebf178fe8",
                      "currency": "EUR",
                      "booking_date": "2020-11-30",
                      "value_date": "2020-11-30",
                      "type_description": "e-maksu",
                      "narrative": "01012019",
                      "message": "01012019",
                      "status": "billed",
                      "reference": "660562087011",
                      "own_message": "01012019",
                      "counterparty_name": "Cross  Sports Club",
                      "transaction_date": "2020-11-30",
                      "payment_date": "2020-11-30",
                      "amount": "-35.00"
                    },
                    {
                      "transaction_id": "a8ab0e96-6ff3-4eaf-be90-4dc007cea87d",
                      "currency": "EUR",
                      "booking_date": "2020-11-30",
                      "value_date": "2020-11-30",
                      "type_description": "Pano",
                      "narrative": "Kiitos",
                      "message": "Kiitos",
                      "status": "billed",
                      "reference": "111144419244",
                      "own_message": "Kiitos",
                      "counterparty_name": "Simon Baker",
                      "transaction_date": "2020-11-30",
                      "payment_date": "2020-11-30",
                      "amount": "2.91"
                    },
                    {
                      "transaction_id": "61bebb1f-02b5-4dc0-8d0d-2e5e243fc7b8",
                      "currency": "EUR",
                      "booking_date": "2020-11-30",
                      "value_date": "2020-11-30",
                      "type_description": "Pano",
                      "narrative": "Lotto",
                      "message": "Lotto",
                      "status": "billed",
                      "reference": "301127019500",
                      "own_message": "Lotto",
                      "counterparty_name": "Salo Ari",
                      "transaction_date": "2020-11-30",
                      "payment_date": "2020-11-30",
                      "amount": "0.10"
                    },
                    {
                      "transaction_id": "a2df78c7-85a1-4640-952f-39f8189e881a",
                      "currency": "EUR",
                      "booking_date": "2020-11-30",
                      "value_date": "2020-11-30",
                      "type_description": "Oma siirto",
                      "narrative": "Lahjat",
                      "message": "Lahjat",
                      "status": "billed",
                      "own_message": "Lahjat",
                      "counterparty_name": "Salo Ari",
                      "transaction_date": "2020-11-30",
                      "payment_date": "2020-11-30",
                      "amount": "4.40"
                    },
                    {
                      "transaction_id": "5df0f4e0-57ec-4b47-934b-0b03482b90a2",
                      "currency": "EUR",
                      "booking_date": "2020-11-30",
                      "value_date": "2020-11-30",
                      "type_description": "Korttiosto",
                      "narrative": "USD 9.39 Gotham City",
                      "message": "USD 9.39 Gotham City",
                      "status": "billed",
                      "reference": "678944335600",
                      "own_message": "USD 9.39 Gotham City",
                      "counterparty_name": "Wallmart",
                      "transaction_date": "2020-11-30",
                      "card_number": "1234.0",
                      "payment_date": "2020-11-30",
                      "original_currency": "USD",
                      "original_currency_amount": "9.39",
                      "currency_rate": "1.1729",
                      "amount": "-8.01"
                    },
                    {
                      "transaction_id": "2a9bebe5-6e51-43d5-ad0c-2d71ee4a04c8",
                      "currency": "EUR",
                      "booking_date": "2020-11-30",
                      "value_date": "2020-11-30",
                      "type_description": "Itsepalvelu",
                      "narrative": "Kino ",
                      "message": "Kino",
                      "status": "billed",
                      "reference": "671232100994",
                      "own_message": "Kino",
                      "counterparty_name": "Salo Johanna",
                      "transaction_date": "2020-11-30",
                      "payment_date": "2020-11-30",
                      "amount": "-0.15"
                    },
                    {
                      "transaction_id": "fc50c79b-aed0-4df6-b22d-3aaa5e0b6c1e",
                      "currency": "EUR",
                      "booking_date": "2020-11-29",
                      "value_date": "2020-12-01",
                      "type_description": "Pano",
                      "narrative": "Lotto",
                      "message": "Lotto",
                      "status": "billed",
                      "reference": "301127019500",
                      "own_message": "Lotto",
                      "counterparty_name": "Salo Ari",
                      "transaction_date": "2020-11-29",
                      "payment_date": "2020-11-29",
                      "amount": "0.04"
                    },
                    {
                      "transaction_id": "8bb0aa02-c21b-45e7-9617-b0e94eb2b50a",
                      "currency": "EUR",
                      "booking_date": "2020-11-29",
                      "value_date": "2020-11-29",
                      "type_description": "Pano",
                      "narrative": "Rent",
                      "message": "Rent",
                      "status": "billed",
                      "reference": "221127019888",
                      "own_message": "Rent",
                      "counterparty_name": "SMM Appartments",
                      "transaction_date": "2020-11-29",
                      "payment_date": "2020-11-29",
                      "amount": "34.10"
                    }
                  ],
            error: {}
        }
    }

    componentDidMount() {
        let { accountId } = this.props.match.params
        fetch(`https://localhost:8443/nordea/accounts/${accountId}/transactions`)
            .then(res => res.json())
            .then(
                (result) => {
                    this.setState({
                        loaded: true,
                        transactions: result.response.transactions
                    })
                },
                (error) => {
                    this.setState({
                        loaded: true,
                        transactions: {},
                        error: error
                    })
                });
    }

    render() {
        return (
            <div>
                {
                    this.state.transactions && this.state.transactions.map(item =>
                        <Transaction key={item.transaction_id} transaction={item} />)
                }
            </div >
        )
    }

}


export default Transactions;


